//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// ?? 4? 28 2020 14:40:35
//
//      Input file      : 
//      Component name  : m_calc
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------


module m_calc(clk, reset, ab, t, n_cons, m, mult_valid, m_valid);
   
   input         clk;
   input         reset;
   input [15:0]  ab;
   input [15:0]  t;
   input [15:0]  n_cons;
   output [15:0] m;
   reg [15:0]    m;
   input         mult_valid;
   output        m_valid;
   reg           m_valid;
   
   
   reg [15:0]    sum_res;
   reg [15:0]    next_sum_res;
   reg           mult_valid_1;
   reg           mult_valid_2;
   wire [31:0]   mult;
   
   assign mult = sum_res * n_cons;
   
   
   always @(posedge clk or reset)
      
      
      begin
         
         if (reset == 1'b1)
         begin
            sum_res <= {16{1'b0}};
            mult_valid_1 <= 1'b0;
            mult_valid_2 <= 1'b0;
         end
         else
         begin
            sum_res <= next_sum_res;
            mult_valid_1 <= mult_valid;
            mult_valid_2 <= mult_valid_1;
         end
      end
   
   
   always @(ab or t or mult_valid_2)
   begin
      m <= mult[15:0];
      next_sum_res <= ab + t;
      m_valid <= mult_valid_2;
   end
   
endmodule
